master:
  installPlugins:
    - kubernetes:latest
    - workflow-job:latest
    - workflow-aggregator:latest
    - credentials-binding:latest
    - git:latest
    - google-oauth-plugin:latest
    - google-source-plugin:latest
    - google-kubernetes-engine:latest
    - google-storage-plugin:latest
    - docker-workflow:latest
    - docker-java-api:latest
    - blueocean:latest
    - configuration-as-code:latest
  resources:
    requests:
      cpu: "50m"
      memory: "1024Mi"
    limits:
      cpu: "1"
      memory: "3500Mi"
  javaOpts: "-Xms3500m -Xmx3500m"
  serviceType: NodePort
agent:
  resources:
    requests:
      cpu: "500m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "512Mi"
persistence:
  size: 100Gi
serviceAccount:
  name: cd-jenkins
backup:
  enabled: true
  componentName: "jenkins-backup"
  schedule: "*/5 * * * *"
  image:
    repository: "maorfr/kube-tasks"
    tag: "0.2.0"
  existingSecret:
    jenkinsaws:
      awsaccesskey: jenkins_aws_access_key
      awssecretkey: jenkins_aws_secret_key
  env:
    - name: "AWS_REGION"
      value: "eu-west-1"
  resources:
    requests:
      memory: 1Gi
      cpu: 1
    limits:
      memory: 1Gi
      cpu: 1
  destination: "s3://dokify-tmp-files-test/jenkins-backup"
rbac:
  create: true
  readSecrets: true
