version: '3.7'

services:
  jenkins:
    privileged: true
    image: dokify/homologation-jenkins:${BUILD}
    hostname: ${JENKINS_HOSTNAME}
    init: true
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        BUILD: ${BUILD:?BUILD required environment}
        JENKINS_HOSTNAME: ${JENKINS_HOSTNAME:?JENKINS_HOSTNAME required environment}
        JENKINS_PORT: ${JENKINS_PORT:?JENKINS_PORT required environment}
        JENKINS_ADMIN_USERNAME: ${JENKINS_ADMIN_USERNAME:?JENKINS_ADMIN_USERNAME required environment}
        JENKINS_ADMIN_PASSWORD: ${JENKINS_ADMIN_PASSWORD:?JENKINS_ADMIN_PASSWORD required environment}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    ports:
      - 8080:${JENKINS_PORT}
