version: '3.7'

services:
  jenkins:
    privileged: true
    image: dokify/homologation-jenkins:${BUILD}
    hostname: ${JENKINS_HOSTNAME}
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        JENKINS_PORT: ${JENKINS_PORT:?JENKINS_PORT required environment}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.kube/config:/home/jenkins/.kube/
    env_file:
      - .env
    ports:
      - 8080:${JENKINS_PORT}
